import {WORLD,REGIONS,BIOME_PALETTE,biomeAt,riverX} from './overworld.js';
import {iconCanvas} from './pixel-icons.js';
import {createGame} from './pixel-game.js';
import {createPixelWorld,drawPortrait,buildingDataURL} from './pixel-world.js';
import {BUILDINGS,CLASSES,RARITIES,TRAITS,MATERIALS,PRODUCTS,RECIPES,DIFFICULTIES,SAVE_KEY} from './pixel-data.js';

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Math.floor(Number(n)||0).toLocaleString('en-US');
let game,world,started=false,modal='',selected=null,portraitCache={},last=0,lastSave=0,leftOpen=true,placing=null;
const $=s=>document.querySelector(s);
const AS=()=>window.PIXEL_ASSETS||{};
const icon=iconCanvas;
const previewMode=new URLSearchParams(location.search).has('preview');
const buildingImages=new Map();
const buildingImg=id=>{if(!buildingImages.has(id))buildingImages.set(id,buildingDataURL(id));return buildingImages.get(id);};
window.addEventListener('pixel-assets-ready',()=>{buildingImages.clear();if(selected)paintInspector();});

function setIcons(root=document){root.querySelectorAll('[data-icon]').forEach(e=>{if(e.firstElementChild?.dataset?.type===e.dataset.icon)return;e.innerHTML='';const c=icon(e.dataset.icon);c.dataset.type=e.dataset.icon;e.append(c);});}
function iconHTML(n){return `<span class="inline-icon" data-icon="${n}"></span>`;}
function logToast(msg,ok=true){const e=document.createElement('div');e.className=`toast${ok?'':' error'}`;e.textContent=msg;$('#toasts').append(e);setTimeout(()=>e.remove(),3300);}
function save(){if(!started||previewMode)return;try{localStorage.setItem(SAVE_KEY,JSON.stringify(game.serialize()));$('#save-label').textContent='已自動儲存';}catch{$('#save-label').textContent='請匯出存檔';}}
function costs(obj){return Object.entries(obj||{}).map(([k,v])=>`<span class="${game.state[k]<v?'short':''}">${iconHTML(k)} ${fmt(v)}</span>`).join('');}
function start(){started=true;game.state.paused=false;$('#start-screen').classList.add('hidden');$('#game-ui').classList.remove('hidden');paint(true);save();}
function resourceRows(){const s=game.state;return [['food','香烤麵包','food'],['drink','莓果飲品','drink'],['bed','舒適床鋪','bed'],['bandage','亞麻繃帶','bandage']].map(([id,n,ic])=>`<button class="stock-item" data-action="craftProduct" data-id="${id}">${iconHTML(ic)}<span>${n}</span><b>${s.stocks[id]}</b><em>製作</em></button>`).join('');}
function miniRoster(){return game.state.hunters.slice(0,3).map(h=>`<button class="mini-hunter" data-action="hunter" data-id="${h.id}"><img data-portrait="${h.id}"><div><strong>${esc(h.name)} <small>Lv.${h.level}</small></strong><p>${esc(h.status)}</p><div class="tiny-health"><span style="width:${Math.max(0,h.hp/h.maxHp*100)}%"></span></div></div></button>`).join('');}
// 圖集載入完成後,立繪快取(portraitCache)必須清掉重畫 —— 
// 不然 UI 永遠顯示圖集載入前生成的舊立繪。(實測踩到:截圖跟舊版逐像素相同)
addEventListener('pixel-assets-ready',()=>{for(const k in portraitCache)delete portraitCache[k];paintPortraits();});
function paintPortraits(){document.querySelectorAll('[data-portrait]').forEach(e=>{const h=game.state.hunters.find(v=>v.id===e.dataset.portrait);if(!h)return;e.src=portrait(h);});}

function paintQuest(){const q=game.state.quest;$('#quest-chapter').textContent=`CHAPTER ${String(q.index+1).padStart(2,'0')}`;$('#quest-title').textContent=q.title;$('#quest-desc').textContent=q.description;$('#quest-progress').textContent=`${q.progress}/${q.target}`;$('#quest-fill').style.width=`${Math.min(100,q.progress/q.target*100)}%`;$('#quest-reward').innerHTML=costs(q.reward);$('#quest-button').textContent=q.claimed?'全部委託完成':q.complete?'領取獎勵':'查看委託';$('#quest-button').disabled=q.claimed;}
function paintInspector(){if(!selected||!BUILDINGS.some(b=>b.id===selected))return;const b=BUILDINGS.find(v=>v.id===selected),s=game.state,l=s.buildings[b.id],p=s.layout[b.id];$('#inspect-title').textContent=b.name;const img=buildingImg(b.id);$('#inspect-content').innerHTML=`<div class="inspect-art">${img?`<img src="${img}" alt="${b.name}">`:iconHTML(b.type)}</div><div class="inspect-level">${l?'建築 Lv.'+l:'尚未建造'}</div><p class="inspect-desc">${b.desc}</p><div class="inspect-effect"><strong>作用</strong><br>${b.effect}</div><div class="cost"><span>需求</span>${costs(l?game.getUpgradeCost(b.id):b.cost)}</div><div class="inspect-actions">${l?`<button class="pixel-button gold" data-action="upgrade" data-id="${b.id}">升級 Lv.${l+1}</button>`:`<button class="pixel-button gold" data-action="construct" data-id="${b.id}">建造</button>`}<button class="move" data-action="moveBuilding" data-id="${b.id}">移動位置</button></div>`;setIcons($('#inspect-content'));}
function paint(force=false){const s=game.state;['gold','wood','ore','gems'].forEach(k=>$('#'+k).textContent=fmt(s[k]));$('#population').textContent=`${s.hunters.length}/${s.capacity}`;$('#town-level').textContent=`村莊 Lv.${s.buildings.hall}`;$('#difficulty-name').textContent=DIFFICULTIES[s.difficulty].name;$('#stock-list').innerHTML=resourceRows();$('#mini-roster').innerHTML=miniRoster();paintPortraits();paintQuest();$('#pause').textContent=s.paused?'▶':'Ⅱ';$('#speed').textContent=`${s.speed}×`;$('#pause-label').classList.toggle('hidden',!s.paused);$('#heal-button').disabled=s.healCooldown>0;$('#heal-label').textContent=s.healCooldown>0?`治癒 ${Math.ceil(s.healCooldown)}s`:'治癒';$('#notice-feed').innerHTML=s.log.slice(0,3).map(l=>`<div>${esc(l.text)}</div>`).join('');if(selected)paintInspector();setIcons();document.body.dataset.kills=s.totalKills;document.body.dataset.services=s.counts.services;const landscape=world?.landscapeStats?.();if(landscape){document.body.dataset.trees=landscape.trees;document.body.dataset.arenas=landscape.arenas;document.body.dataset.roads=landscape.roads;}document.body.dataset.worldArea=WORLD.area;document.body.dataset.region=s.region;const rb=$('#region-badge');if(rb)rb.textContent=(REGIONS.find(r=>r.id===s.region)?.name||'向陽草原')+' · 狩獵中';if($('#minimap-v3'))paintMap($('#minimap-v3'),true);}
function modalTitle(t,ic='scroll'){const names={worldmap:'主世界地圖 · 三倍探索面積',build:'村莊建設',hunters:'獵人名冊',trade:'交易所',craft:'製作與庫存',dungeon:'地下城遠征',arena:'競技場模擬對戰',quests:'村長委託',inventory:'村莊倉庫',difficulty:'狩獵難度',settings:'遊戲設定',help:'村長入門手札',boss:'地圖首領'};$('#modal-title').textContent=names[t]||t;$('#modal-icon').dataset.icon=ic;setIcons($('#modal'));}
function portrait(h){const key=h.classId+':'+h.rarity;if(portraitCache[key])return portraitCache[key];const c=document.createElement('canvas');c.width=84;c.height=96;drawPortrait(c,h,{scale:2.7});return portraitCache[key]=c.toDataURL();}

function openModal(type){modal=type;$('#modal-backdrop').classList.remove('hidden');modalTitle(type,type==='trade'?'trade':type==='craft'?'anvil':type==='dungeon'?'dungeon':type==='arena'?'swords':type==='hunters'?'hunter':type==='difficulty'?'skull':'scroll');$('#modal-content').innerHTML=modalHTML(type);if(type==='worldmap')paintMap($('#world-map-canvas'));setIcons($('#modal-content'));paintPortraits();}
function closeModal(){modal='';$('#modal-backdrop').classList.add('hidden');}
function modalHTML(type){const s=game.state;
 if(type==='worldmap')return `<div class="world-map-header"><span>主世界 · 8 個區域</span><b>${WORLD.width} × ${WORLD.height} = ${WORLD.area.toLocaleString()} 地圖單位</b><button class="pixel-button" data-action="worldOverview">全景查看</button></div><canvas id="world-map-canvas" width="760" height="390" aria-label="三倍大主世界區域地圖"></canvas><div class="region-grid">${REGIONS.map(r=>`<article class="region-card ${s.region===r.id?'active':''}" style="--biome:${r.color}"><h3>${r.name}</h3><small>${r.subtitle}</small><p>${r.description}</p><div><button class="pixel-button" data-action="regionView" data-id="${r.id}">查看</button>${r.id!=='village'?`<button class="pixel-button gold" data-action="regionTravel" data-id="${r.id}">前往${r.name}</button>`:''}</div></article>`).join('')}</div><p class="modal-note">參考主世界的生態分區與河流配置。獵人沿橋樑通行；這個版本不含挖掘、放置方塊或無限地形。</p>`;

 if(type==='build')return `<p class="modal-intro">村長可以自由建造和升級設施。把建築移到喜歡的位置，讓獵人往返更順暢。</p><div class="building-grid">${BUILDINGS.map(b=>{const l=s.buildings[b.id];return `<button class="building-card ${l?'':'unbuilt'}" data-action="selectBuilding" data-id="${b.id}"><img src="${buildingImg(b.id)}" alt="${b.name}"><strong>${b.name}</strong><small>${l?'Lv.'+l:'未建造'}</small><b class="build-level">${l?'◆':''}</b></button>`}).join('')}</div>`;
 if(type==='hunters')return `<div class="modal-toolbar"><span>性格、稀有度、裝備與需求都會影響狩獵結果。</span><button class="pixel-button gold" data-action="recruit">招募訪客</button></div><div class="roster-grid">${s.hunters.map(h=>`<button class="hunter-card" data-action="hunter" data-id="${h.id}"><img data-portrait="${h.id}"><div><h3>${esc(h.name)}</h3><small>Lv.${h.level} · ${CLASSES.find(c=>c.id===h.classId)?.name}</small><div class="rarity" style="--rarity:${RARITIES.find(r=>r.id===h.rarity)?.color}">${RARITIES.find(r=>r.id===h.rarity)?.name}</div><div class="status">${esc(h.status)}</div><div class="tiny-health"><span style="width:${h.hp/h.maxHp*100}%"></span></div></div></button>`).join('')}</div><p class="modal-note">獵人擁有自己的金幣，會購買餐點、飲品、床鋪、繃帶與裝備。</p>`;
 if(type==='recruit')return `<p class="modal-intro">旅人會隨時間來到村莊。邀請更稀有的獵人加入，他們會帶著不同的性格與成長潛力。</p><div class="visitor-grid">${s.visitors.map(v=>{const c=CLASSES.find(x=>x.id===v.classId),r=RARITIES.find(x=>x.id===v.rarity),t=TRAITS.find(x=>x.id===v.trait);return `<article class="visitor-card"><div class="visitor-art"><img src="${portrait({id:v.id,classId:v.classId})}" alt="${c.name}"></div><h3>${c.name}</h3><div class="rarity" style="--rarity:${r.color}">${r.name}</div><div class="trait">${t.name} · ${t.desc}</div><p>${c.desc}</p><button class="pixel-button gold" data-action="recruitVisitor" data-id="${v.id}">邀請加入 ${v.cost} 金幣</button></article>`}).join('')}</div>`;
 if(type==='trade')return `<p class="modal-intro">向獵人發布收購委託。他們會在狩獵後回村出售戰利品，村莊支付金幣並獲得材料。</p><div class="materials-grid">${Object.entries(MATERIALS).map(([id,m])=>`<div class="material-item">${iconHTML(id)}<div><span>${m.name}</span><b>${s[id]}</b></div><small>${m.price} 金幣/份</small></div>`).join('')}</div><table class="trade-table"><thead><tr><th>材料</th><th>收購中</th><th>調整數量</th><th>操作</th></tr></thead><tbody>${Object.entries(MATERIALS).map(([id,m])=>`<tr><td>${m.name}</td><td>${s.tradeRequests[id]} 份</td><td><input id="trade-${id}" type="number" min="0" max="999" value="${s.tradeRequests[id]}"></td><td><button class="pixel-button" data-action="setTrade" data-id="${id}">發布</button></td></tr>`).join('')}</tbody></table><div class="trade-footer"><span>收購金額會從村莊金庫支付。<br>獵人會在下一次回村時自動交易。</span><button class="pixel-button gold" data-action="collectTrade">查看交易紀錄</button></div>`;
 if(type==='craft')return `<p class="modal-intro">把材料轉成獵人需要的生活物資與裝備。服務會由獵人付費，回到村莊金庫。</p><div class="tabs"><button class="active">生活物資</button><button>裝備製作</button></div><div class="craft-grid">${Object.entries(PRODUCTS).map(([id,p])=>`<article class="craft-card"><div class="craft-heading"><i>${iconHTML(id)}</i><div><h3>${p.name}</h3><small>庫存 ${s.stocks[id]} · 售價 ${p.price}</small></div></div><p>${p.need==='hp'?'治療生命':p.need==='satiety'?'恢復飽食度':p.need==='stamina'?'恢復精力':'恢復心情'}，旅館與商店建築升級後效果更佳。</p><div class="cost">${costs(p.cost)}</div><div class="craft-buttons"><button class="pixel-button gold" data-action="craftProduct" data-id="${id}">製作 10 份</button><button class="pixel-button" data-action="craftProduct" data-id="${id}" data-batches="5">製作 50 份</button></div></article>`).join('')}</div><div class="craft-grid" style="margin-top:14px">${RECIPES.map(r=>`<article class="craft-card"><div class="craft-heading"><i>${iconHTML('anvil')}</i><div><h3>${r.name}</h3><small>裝備庫存 ${s.gearStock[r.type]} · 售價 ${r.price}</small></div></div><p>獵人返回村莊後會用個人金幣購買，裝備提升攻擊或防禦。</p><div class="cost">${costs(r.cost)}</div><button class="pixel-button gold" data-action="craftGear" data-id="${r.id}">鍛造裝備</button></article>`).join('')}</div>`;
 if(type==='dungeon')return `<div class="encounter-banner"><i>${iconHTML('dungeon')}</i><div><h3>地下城遠征</h3><p>選派三位獵人深入地下城。每層都有新的敵人與材料獎勵。</p></div></div><div class="encounter-status">${s.dungeon.active?`第 ${s.dungeon.floor} 層 · ${s.dungeon.phase}`:`最高紀錄：第 ${s.dungeon.bestFloor} 層 · ${s.dungeon.cooldown>0?'整備中':'可以出發'}`}</div><div class="party-grid">${s.hunters.map(h=>`<button class="party-pick ${s.dungeon.hunterIds.includes(h.id)?'selected':''}" data-action="toggleDungeonHunter" data-id="${h.id}"><img data-portrait="${h.id}"><span>${h.name}<b>Lv.${h.level}</b></span><small>${s.dungeon.hunterIds.includes(h.id)?'✓':''}</small></button>`).join('')}</div><div class="encounter-actions"><button class="pixel-button gold" data-action="startDungeon">${s.dungeon.active?'探險中…':'派遣三人小隊'}</button></div>`;
 if(type==='arena')return `<div class="encounter-banner"><i>${iconHTML('swords')}</i><div><h3>競技場模擬對戰</h3><p>與 NPC「${s.arena.opponent}」進行三人小隊模擬戰，不消耗真實死亡資源。</p></div></div><div class="encounter-status">勝場 ${s.arena.wins} · 敗場 ${s.arena.losses} · ${s.arena.active?s.arena.phase:s.arena.cooldown>0?'整備中':'可挑戰'}</div><div class="party-grid">${s.hunters.map(h=>`<button class="party-pick ${s.arena.hunterIds.includes(h.id)?'selected':''}" data-action="toggleArenaHunter" data-id="${h.id}"><img data-portrait="${h.id}"><span>${h.name}<b>Lv.${h.level}</b></span><small>${s.arena.hunterIds.includes(h.id)?'✓':''}</small></button>`).join('')}</div><div class="encounter-actions"><button class="pixel-button gold" data-action="startArena">開始模擬對戰</button></div>`;
 if(type==='quests')return `<div class="quest-list">${s.quest.claimed?'<p class="modal-note">全部委託已完成。新的村莊傳說正在等待被書寫。</p>':`<article class="quest-list-row"><h3>${s.quest.title}</h3><p>${s.quest.description}</p><div class="progress"><span style="width:${s.quest.progress/s.quest.target*100}%"></span><b>${s.quest.progress}/${s.quest.target}</b></div><div class="cost">獎勵 ${costs(s.quest.reward)}</div><button class="pixel-button gold" data-action="quest" ${s.quest.complete?'':'disabled'}>${s.quest.complete?'領取獎勵':'尚未完成'}</button></article>`}</div>`;
 if(type==='inventory')return `<p class="modal-intro">村莊倉庫保存建材、生活物資與鐵匠鋪製作的裝備。</p><div class="materials-grid">${Object.entries({...MATERIALS,food:{name:'香烤麵包'},drink:{name:'莓果飲品'},bed:{name:'舒適床鋪'},bandage:{name:'亞麻繃帶'},weapon:{name:'精鐵武器'},armor:{name:'皮革護甲'}}).map(([id,m])=>`<div class="material-item">${iconHTML(id)}<div><span>${m.name}</span><b>${s[id]??s.stocks?.[id]??s.gearStock?.[id]??0}</b></div></div>`).join('')}</div>`;
 if(type==='difficulty')return `<p class="modal-intro">狩獵難度會提高森林魔物的生命與攻擊。高難度需要完成轉世累計。</p><div class="difficulty-grid">${DIFFICULTIES.map(d=>`<article class="difficulty-card"><i>${iconHTML('skull')}</i><h3>${d.name}</h3><small>魔物強度 ×${d.mult}<br>需要轉世 ${d.rebirths} 次</small><button class="pixel-button ${s.difficulty===d.id?'gold':''}" data-action="setDifficulty" data-id="${d.id}" ${s.difficulty===d.id?'disabled':''}>${s.difficulty===d.id?'目前難度':'選擇'}</button></article>`).join('')}</div>`;
 if(type==='settings')return `<div class="setting-row"><div><strong>音效與畫面</strong><small>像素渲染會保持硬邊與原始色塊。</small></div><button class="pixel-button" data-action="quality">切換畫質</button></div><div class="setting-row"><div><strong>匯出存檔</strong><small>將整個村莊、獵人、地下城進度備份成 JSON。</small></div><button class="pixel-button gold" data-action="export">匯出</button></div><div class="setting-row"><div><strong>重新開始</strong><small>清除目前存檔並從五位初始獵人開始。</small></div><button class="pixel-button danger" data-action="reset">重置</button></div>`;
 if(type==='help')return `<div class="help-grid"><div class="help-card"><h3>村長要做什麼？</h3><p>重建被魔王摧毀的城鎮，建造餐廳、旅館、酒館、治療所與鐵匠鋪，服務獵人的生活需求。</p></div><div class="help-card"><h3>獵人怎麼生活？</h3><p>獵人有自己的金幣、飽食度、心情與精力。他們會狩獵、帶回材料、回村交易，再支付費用吃飯、休息和治療。</p></div><div class="help-card"><h3>怎麼變強？</h3><p>在學院學技能、修煉地訓練、鐵匠鋪購買武器，再到強化精煉所強化。Lv.100 後可到復活聖所轉世。</p></div><div class="help-card"><h3>村外內容</h3><p>委託所追蹤魔物目標，地下城三人遠征，地圖首領討伐，以及修煉地開放的 NPC 競技場模擬對戰。</p></div></div>`;
 if(type==='boss')return `<div class="encounter-banner"><i>${iconHTML('horn')}</i><div><h3>地圖首領：森林魔王</h3><p>吹響號角，召集所有可出征的獵人。首領會帶回大量稀有材料與星晶。</p></div></div><div class="encounter-status">${s.expedition.active?`討伐中 · 生命 ${Math.ceil(s.expedition.bossHp)}/${s.expedition.bossMaxHp}`:s.expedition.cooldown>0?`整備 ${Math.ceil(s.expedition.cooldown)} 秒`:'森林魔王尚未出現'}</div><div class="encounter-actions"><button class="pixel-button gold" data-action="startBoss" ${s.expedition.active||s.expedition.cooldown>0?'disabled':''}>召喚森林魔王</button></div>`;
 return '';
}

function selectedIds(kind){return game.state[kind].hunterIds||[];}
function toggleParty(kind,id){const list=selectedIds(kind),i=list.indexOf(id);if(i>=0)list.splice(i,1);else if(list.length<3)list.push(id);openModal(kind==='dungeon'?'dungeon':'arena');}
function inspect(id){selected=id;$('#inspector').classList.remove('hidden');paintInspector();world?.setSelected(id);}
function doAction(el){const a=el.dataset.action,id=el.dataset.id;let r;
 if(a==='worldmap')return openModal('worldmap');
 if(a==='worldOverview'){closeModal();world.focus('world');return;}
 if(a==='regionView'){closeModal();world.focus(id==='village'?'home':'region:'+id);return;}
 if(a==='regionTravel'){r=game.exploreRegion(id);logToast(r.message,r.ok);if(r.ok){closeModal();world.focus('region:'+id);save();}paint();return;}
 if(a==='start')return start();if(a==='close')return closeModal();if(a==='toggleLeft'){leftOpen=!leftOpen;$('#left-panel').classList.toggle('hidden',!leftOpen);$('#reopen-left').classList.toggle('hidden',leftOpen);return;}if(a==='closeInspector'){$('#inspector').classList.add('hidden');selected=null;world?.setSelected(null);return;}
 if(a==='home'){closeModal();world?.focus('home');return;}if(a==='hunt'){world?.focus('hunt');return;}if(a==='zoomIn'){world?.zoomBy(1.15);return;}if(a==='zoomOut'){world?.zoomBy(1/1.15);return;}
 if(a==='pause'){game.state.paused=!game.state.paused;paint();return;}if(a==='speed'){game.state.speed=game.state.speed>=3?1:game.state.speed+1;paint();return;}
 if(a==='settings'||a==='help'||a==='build'||a==='hunters'||a==='recruit'||a==='trade'||a==='craft'||a==='dungeon'||a==='arena'||a==='quests'||a==='inventory'||a==='difficulty'||a==='boss')return openModal(a==='boss'?'boss':a);
 if(a==='selectBuilding'){closeModal();inspect(id);world?.focus(id);return;}if(a==='upgrade'){r=game.upgrade(id);logToast(r.message,r.ok);paint();return;}if(a==='construct'){r=game.construct(id);logToast(r.message,r.ok);paint();return;}
 if(a==='learnSkill'){r=game.learnSkill(id);logToast(r.message,r.ok);openHunter(id);paint();return;}if(a==='train'){r=game.train(id);logToast(r.message,r.ok);openHunter(id);paint();return;}if(a==='enhanceHunter'){r=game.enhance(id);logToast(r.message,r.ok);openHunter(id);paint();return;}if(a==='reincarnate'){r=game.reincarnate(id);logToast(r.message,r.ok);openHunter(id);paint();return;}
 if(a==='moveBuilding'){placing=id;$('#placement').classList.remove('hidden');$('#placement-label').textContent=`拖曳或點擊空地放置「${BUILDINGS.find(b=>b.id===id)?.name}」`;world?.placeMode(id);return;}if(a==='cancelMove'){placing=null;$('#placement').classList.add('hidden');world?.placeMode(null);return;}
 if(a==='quest'){r=game.claimQuest();if(!r.ok&&game.state.quest.index===0)openModal('recruit');else logToast(r.message,r.ok);paint();return;}if(a==='recruitVisitor'){r=game.recruit(id);logToast(r.message,r.ok);if(r.ok)openModal('recruit');paint();return;}if(a==='recruit'){return openModal('recruit');}
 if(a==='hunter'){openHunter(id);return;}
 if(a==='craftProduct'){r=game.craft(id,Number(el.dataset.batches||1));logToast(r.message,r.ok);if(modal==='craft')openModal('craft');paint();return;}if(a==='craftGear'){r=game.craftEquipment(id);logToast(r.message,r.ok);openModal('craft');paint();return;}
 if(a==='setTrade'){const v=Number($(`#trade-${id}`).value);r=game.setTradeRequest(id,v);logToast(r.message,r.ok);return;}if(a==='collectTrade'){logToast('交易所會在獵人返村時自動完成收購。');return;}
 if(a==='heal'){r=game.heal();logToast(r.message,r.ok);paint();return;}if(a==='startBoss'){r=game.expedition();logToast(r.message,r.ok);closeModal();paint();return;}
 if(a==='toggleDungeonHunter'){toggleParty('dungeon',id);return;}if(a==='toggleArenaHunter'){toggleParty('arena',id);return;}if(a==='startDungeon'){r=game.startDungeon(game.state.dungeon.hunterIds);logToast(r.message,r.ok);paint();return;}if(a==='startArena'){r=game.startArena(game.state.arena.hunterIds);logToast(r.message,r.ok);paint();return;}
 if(a==='setDifficulty'){r=game.setDifficulty(Number(id));logToast(r.message,r.ok);if(r.ok)closeModal();paint();return;}
 if(a==='quality'){world?.setQuality(false);logToast('已切換像素省電模式。');return;}if(a==='reset'){if(confirm('確定要重置村莊嗎？')){game.reset();started=true;paint(true);logToast('五位獵人重新抵達暮影村。');}return;}
 if(a==='export'){const blob=new Blob([JSON.stringify(game.serialize())],{type:'application/json'}),u=URL.createObjectURL(blob),link=document.createElement('a');link.href=u;link.download='暮影村-像素存檔.json';link.click();setTimeout(()=>URL.revokeObjectURL(u),500);return;}
}
function openHunter(id){const h=game.state.hunters.find(v=>v.id===id);if(!h)return;modal='hunter-detail';modalTitle('hunter','hunter');$('#modal-content').innerHTML=`<div class="hunter-detail"><div class="detail-avatar"><img src="${portrait(h)}"><h3>${esc(h.name)}</h3><div class="rarity" style="--rarity:${RARITIES.find(r=>r.id===h.rarity)?.color}">${RARITIES.find(r=>r.id===h.rarity)?.name}</div></div><div><div class="detail-header"><strong>${CLASSES.find(c=>c.id===h.classId)?.name} · Lv.${h.level}</strong><span>${esc(h.status)}</span></div><div class="stats-grid"><div>攻擊<b>${h.attack}</b></div><div>防禦<b>${h.defense}</b></div><div>轉世<b>${h.rebirths}</b></div></div>${[['hp','生命','hp'],['satiety','飽食','satiety'],['stamina','精力','stamina'],['mood','心情','mood']].map(([k,n,c])=>`<div class="need-row ${c}"><label>${n}</label><div class="progress"><span style="width:${k==='hp'?h.hp/h.maxHp*100:h[k]}%"></span><b>${Math.floor(k==='hp'?h.hp:h[k])}</b></div></div>`).join('')}<div class="equipment-row">${iconHTML('gold')} 個人金幣 ${fmt(h.gold)}　 ${h.equipment.weapon?'⚔️ 武器':'未裝備武器'}　${h.equipment.armor?'🛡️ 護甲':'未裝備護甲'}</div></div></div><div class="hunter-actions"><button class="pixel-button" data-action="learnSkill" data-id="${h.id}">學習技能<small>學院</small></button><button class="pixel-button" data-action="train" data-id="${h.id}">修煉<small>20 個人金幣</small></button><button class="pixel-button" data-action="enhanceHunter" data-id="${h.id}">強化裝備<small>精煉所</small></button><button class="pixel-button" data-action="reincarnate" data-id="${h.id}">轉世<small>Lv.100</small></button></div>`;setIcons($('#modal-content'));$('#modal-backdrop').classList.remove('hidden');}
function handleWorldSelect(id){if(!started)return;if(id?.startsWith('hunter:'))openHunter(id.slice(7));else if(id)inspect(id);}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el&&!el.disabled)doAction(el);});
document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select'))return;if(e.key.toLowerCase()==='m'&&started){openModal('worldmap');return;}if(e.key==='Escape'){if(placing){placing=null;$('#placement').classList.add('hidden');world?.placeMode(null);}else closeModal();}if(e.code==='Space'&&!modal&&started){e.preventDefault();game.state.paused=!game.state.paused;paint();}const map={'1':'build','2':'hunters','3':'trade','4':'craft','5':'dungeon','6':'arena','7':'quests'};if(!modal&&map[e.key])openModal(map[e.key]);});
$('#modal-backdrop').addEventListener('click',e=>{if(e.target.id==='modal-backdrop')closeModal();});
try{const saved=(()=>{try{return previewMode?null:JSON.parse(localStorage.getItem(SAVE_KEY)||'null');}catch{return null;}})();game=createGame(saved);game.state.paused=true;if(saved)$('#start-button').innerHTML='繼續村莊生活 <span>▶</span>';document.querySelector('#title-art').style.backgroundImage=`url(${AS().title||''})`;setIcons();world=createPixelWorld($('#world'),{getState:()=>game.state,onSelect:handleWorldSelect,onPlace:(id,x,z)=>{const r=game.moveBuilding(id,x,z);logToast(r.message,r.ok);if(r.ok){placing=null;$('#placement').classList.add('hidden');world.placeMode(null);}paint();}});world.setTime(.18);window.addEventListener('resize',()=>world.resize());window.addEventListener('pagehide',save);const load=$('#loading');load.style.opacity='0';setTimeout(()=>load.remove(),500);let previous=performance.now(),frameTime=0,frames=0,fpsStart=performance.now();function frame(now){requestAnimationFrame(frame);if(document.hidden){previous=now;return;}if(now-frameTime<1000/40)return;frameTime=now;frames++;if(now-fpsStart>2000){document.body.dataset.fps=Math.round(frames*1000/(now-fpsStart));fpsStart=now;frames=0;}const dt=Math.min(.1,(now-previous)/1000);previous=now;if(started)game.tick(dt);world.setTime((game.state.time%240)/240);world.update(game.state.paused?0:dt,game.state);if(now-last>250){paint();last=now;}if(now-lastSave>5000){save();lastSave=now;}}requestAnimationFrame(frame);}catch(err){console.error(err);$('#loading').innerHTML='<b>像素村莊載入失敗，請重新整理</b>';}

function paintMap(canvas,mini=false){
 if(!canvas)return;const g=canvas.getContext('2d');g.imageSmoothingEnabled=false;const w=canvas.width,h=canvas.height,margin=mini?4:15,sx=(w-margin*2)/WORLD.width,sy=(h-margin*2)/WORLD.height;
 g.fillStyle='#273b35';g.fillRect(0,0,w,h);
 for(let z=WORLD.minZ;z<WORLD.maxZ;z+=1)for(let x=WORLD.minX;x<WORLD.maxX;x+=1){const terrain=biomeAt(x,z);g.fillStyle=BIOME_PALETTE[terrain];if((x*17+z*31)%11===0&&!['ocean','river','ice','bridge'].includes(terrain))g.fillStyle=terrain==='snow'?'#f1f4e4':terrain==='desert'?'#e9c993':terrain==='mountain'?'#bfc3b6':'#7c9c56';g.fillRect(Math.floor(margin+(x-WORLD.minX)*sx),Math.floor(margin+(z-WORLD.minZ)*sy),Math.ceil(sx),Math.ceil(sy));}
 const to=(x,z)=>[margin+(x-WORLD.minX)*sx,margin+(z-WORLD.minZ)*sy];
 for(const b of BUILDINGS){if(!game.state.buildings[b.id])continue;const p=game.state.layout[b.id],q=to(p.x,p.z);g.fillStyle='#efe1af';g.fillRect(q[0]-3,q[1]-2,6,4);}
 for(const r of REGIONS){const[x,y]=to(r.x,r.z);g.fillStyle=r.id===game.state.region?'#ffe182':'#344634';g.fillRect(x-3,y-3,6,6);if(!mini){g.font='bold 12px Microsoft JhengHei';g.textAlign='center';const tw=g.measureText(r.name).width;g.fillStyle='#233428dd';g.fillRect(x-tw/2-4,y+6,tw+8,19);g.fillStyle='#ffebbd';g.fillText(r.name,x,y+20);}}
 if(mini)for(const h of game.state.hunters){const[x,y]=to(h.x,h.z);g.fillStyle='#fff7da';g.fillRect(x-1,y-1,3,3);}
}
